### ISSUE TITLE
How could we test the parameter store backup?

### ISSUE THREAD

**Issue by bryophyta** [guardian/frontend-lambda#39]
Do we have confidence that we could restore our parameter store from the backup?

Do we know whether this has been tested, and what it would require?

```[tasklist]
- [ ] https://github.com/guardian/frontend-lambda/issues/46
- [ ] Add documentation on how to back up parameter store / how to restore a backup
```

**Comment by rhiannareechaye** [comment]
@ParisaTork please could you update on the status of this ticket prior to our rota planning which is on Tuesday?

**Comment by Georges-GNM** [comment]
@OllysCoding or @DanielCliftonGuardian sounds like you may have been working on the documentation for this with James, is that right? Any updates if so?

**Comment by jamesgorrie** [comment]
We could have a dry run of this, but we haven't had the time. It has never came up as an issue, so we might add this as part of the runbook work we're doing
